[ req ]
default_bits        = 4096
default_md          = sha256
distinguished_name  = ca_dn
req_extensions      = req_ext
prompt              = no

[ ca_dn ]
C  = TH
ST = Bangkok
L  = Bangkok
O  = Local Development CA
CN = Local Development Root CA

[ req_ext ]
# Empty section for compliance with system defaults
