[ req ]
default_bits        = 4096
default_md          = sha256
distinguished_name  = ca_dn
prompt              = no

[ ca_dn ]
C  = TH
ST = Bangkok
L  = Bangkok
O  = Local Development CA
CN = Local Development Root CA
